WIP!holand
swaponline/MultiCurrencyWallet pull request #3175
Opened 2020-08-14 01:30 UTC by Pasha8914

# Pull request

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Styleguide check `npm run validate`
- [x] Good naming
- [x] Keep simple
- [x] I checked desktop/mobile version
- [x] I checked bright/dark mode
- [x] I checked en/ru version
- [x] Affects money; I checked the functionality once again
- [x] Video or screenshot attached
- [x] Testing instruction attached
- [x] I checked the PR once again

complete 
![image](https://user-images.githubusercontent.com/43392281/90202621-87b08100-de21-11ea-9657-f76e301cd7b5.png)

### Description

### Video or screenshot

### What and how to test

To test it locally run ```git fetch && fit checkout twelveWordsCreateBug``` where twelveWordsCreateBug is a name of this branch (see under title) OR ```PRID=2812; git fetch origin refs/pull/$PRID/merge:pr$PRID && git checkout pr$PRID``` where PRID is number of this pull request

```npm i && npm run build:mainnet``` then run MultiCurrencyWallet/build.mainnet/index.html in browse

2020-08-19 14:31 UTC, Pasha8914 commented on shared/components/modals/InfoPay/InfoPay.js
> -                <span> <FormattedMessage id="InfoPay_2" defaultMessage="были успешно переданы" />
2 разных текста должны иметь разные айди или быть с 1 айди, но тогда с одинаковым текстом, поэйтому сорян, не в рамках пула, но мешало сделать экстракт

2020-08-19 14:31 UTC, Pasha8914 commented on shared/pages/PointOfSell/PointOfSell.js
> +      id="ExchangeTitleTag1_point_of_sell"
2 разных текста должны иметь разные айди или быть с 1 айди, но тогда с одинаковым текстом, поэйтому сорян, не в рамках пула, но мешало сделать экстракт

2020-08-19 14:31 UTC, Pasha8914 commented on shared/pages/PointOfSell/PointOfSell.js
> +              <FormattedMessage id="continueDeclined977_point_of_sell" defaultMessage="Click here to continue your swaps" />
2 разных текста должны иметь разные айди или быть с 1 айди, но тогда с одинаковым текстом, поэйтому сорян, не в рамках пула, но мешало сделать экстракт

2020-08-19 14:31 UTC, Pasha8914 commented on shared/pages/Swap/SwapProgress/SwapProgressText/GhostToBtc.js
> +          <FormattedMessage id="ethToBtcText20_ghost_to_btc" defaultMessage="Waiting for GHOST Owner to create Secret Key, create GHOST Script and charge it" />
берем и делаем поиск  по этой строке и смотрим на комментарии выше, сделал разные айди, НО НУЖНО СДЕЛАТЬ ТАК 

          ```<FormattedMessage id="ethToBtcText20_ghost_to_btc" defaultMessage="Waiting for {currency} Owner to create Secret Key, create {currency} Script and charge it" values={{ currency: "GHOST" }}  />```

и так далее, смотреть то где я менял айди, сразу скажу -  я парень простой и наклипал везде разные айди, где я считал, что могут возникнуть у меня проблемы, поэтому не серчайте, но я убежден, что тут норм должен сделать тот, кто создал эту строку

некий @JoaoCampos89, a month ago   (July 9th, 2020 12:31pm)

2020-08-19 14:38 UTC, Pasha8914 commented on shared/pages/Swap/SwapProgress/SwapProgressText/GhostToBtc.js
> +          <FormattedMessage id="ethToBtcText20_ghost_to_btc" defaultMessage="Waiting for GHOST Owner to create Secret Key, create GHOST Script and charge it" />
@ Joao Campos 89 Dude "id" it's an uniq identifier, make plz them uniq. 
this means - if you use 2 texts, their IDs must be different, if you use the same IDs, you must use different text, but if 
use
 <FormattedMessage id="ethToBtcText20_ghost_to_btc" defaultMessage="Waiting for {currency} Owner to create Secret Key, create {currency} Script and charge it" values={{ currency: "GHOST" }}  />

i didnt fixed it, bsc thing thats is your area of ​​responsibility

2020-08-19 15:23 UTC, shendel approved these changes

2020-08-20 06:31 UTC, iower requested changes

2020-08-20 06:31 UTC, iower commented on shared/containers/IntlProviderContainer.js
> +              console.log("123", props.match.params.locale)
```suggestion
```

2020-08-20 06:31 UTC, iower commented on shared/containers/IntlProviderContainer.js
> +            console.log({ messages, currentLocale })
```suggestion
```

2020-08-20 10:59 UTC, iower approved these changes

2020-08-20 11:00 UTC, merged