Cleanup
swaponline/MultiCurrencyWallet pull request #3509
Opened 2020-10-30 19:58 UTC by iower

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Styleguide check `npm run validate`
- [x] Good naming, keep simple
- [ ] Tested desktop/mobile
- [ ] Tested bright/dark
- [ ] Tested en/ru
- [ ] Affects money; I checked the functionality once again
- [x] I checked the PR once again

Weekend cleanup

2020-10-30 21:21 UTC, noxonsu commented
https://github.com/swaponline/MultiCurrencyWallet/pull/3509/checks?check_run_id=1333877205 чет не собралось

2020-11-02 22:48 UTC, shendel requested changes
.

2020-11-02 22:48 UTC, shendel commented on package.json
> +    "linter": "lint-diff",
масло масленое

2020-11-02 22:48 UTC, shendel commented on package.json
> +      "post-commit": "npm run common:test && npm run core:test && npm run linter"
без DEBUG.... - а оно вообще работает? 
![image](https://user-images.githubusercontent.com/1880211/97927729-9fd7d280-1d76-11eb-9d95-554d8aba95b8.png)

2020-11-02 22:48 UTC, shendel requested changes
.

2020-11-04 07:13 UTC, noxonsu commented
@iower any updates?

2020-11-04 09:16 UTC, iower commented on package.json
> +    "linter": "lint-diff",
Removed

2020-11-04 09:17 UTC, iower commented on package.json
> +      "post-commit": "npm run common:test && npm run core:test && npm run linter"
Вidn't understand what the problem, but removed

2020-11-04 10:03 UTC, noxonsu approved these changes

2020-11-04 10:03 UTC, merged