First screen: add restore link + refactoring
swaponline/MultiCurrencyWallet pull request #3512
Opened 2020-11-02 10:47 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Styleguide check `npm run validate`
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
#3505

### Video / screenshot proof
![image](https://user-images.githubusercontent.com/61930014/97859572-c7f61000-1d3b-11eb-9e6d-6904b3cf59d8.png)

2020-11-02 22:17 UTC, shendel requested changes

2020-11-02 22:17 UTC, shendel commented on src/front/client/index.html
> +                window.setTimeout(() => {
there no ecma - its native script with back-compatibility. revert code and return back dot with comma

2020-11-02 22:26 UTC, shendel requested changes
.

2020-11-02 22:26 UTC, shendel commented on src/front/shared/pages/CreateWallet/CreateWallet.js
> +  const currencyBalance = [btcData, btcMultisigSMSData, btcMultisigUserData, ethData, ghostData, nextData].map(({ balance, currency, infoAboutCurrency }) => ({
это не читабельно, я разбивал по строчкам чтобы не путаться в массиве данных

2020-11-02 23:11 UTC, shendel requested changes
.

2020-11-02 23:11 UTC, shendel commented on src/front/shared/pages/CreateWallet/CreateWallet.js
> -  const btnRestoryWallet = document.querySelector('.starter-modal__link_restore-wallet')
один из бывших разработчиков с пеной у рта бы спорил на счет "stupied"
В двух словах
1. подгружается индекс
2. инициализация реакта
3. на кнопку (.starter-modal__link_restore-wallet) вешается обработчик, который при клике вызывает окно (реакта) восстановление кошелька

2020-11-02 23:12 UTC, shendel commented on src/front/shared/pages/CreateWallet/CreateWallet.js
> -  const btnRestoryWallet = document.querySelector('.starter-modal__link_restore-wallet')
кнопки с таким классом в index.html уже давно нет, но это не "stupied",

2020-11-02 23:17 UTC, shendel commented on src/front/shared/pages/CreateWallet/CreateWallet.js
> -  const btnRestoryWallet = document.querySelector('.starter-modal__link_restore-wallet')
Так что этот код имеет место быть (клиенты сами могут добавить кнопку с таким классом к себе на индекс), с правками (выбор элемента в DidMount, проверки наличия элемента, а потом обработчик событий)

2020-11-02 23:23 UTC, shendel requested changes
.

2020-11-02 23:23 UTC, shendel commented on src/front/client/index.html
> +        const btnRestoryWallet = document.querySelector('.starter-modal__restore-wallet')
опять-же - масло-масленое, в чем смысл переименовать "....modal__link_restore..." в "...modal__restore...", и готовый код перенести из одного места (CreateWallet) в другое?

2020-11-02 23:28 UTC, shendel commented on src/front/client/index.html
> +        const btnRestoryWallet = document.querySelector('.starter-modal__restore-wallet')
конкретно этот коммит https://github.com/swaponline/MultiCurrencyWallet/pull/3512/commits/71e40f5fb91dd004270ee25a5ef295232a9242f6 "Add hundlers on first sreen link for restore wallet" и вот этот https://github.com/swaponline/MultiCurrencyWallet/pull/3512/commits/893c7350a4e4e8e4ed22cb4ccb79c3e79f7f74e8 - в чем разница?

2020-11-03 07:24 UTC, NotEternal commented on src/front/shared/pages/CreateWallet/CreateWallet.js
> -  const btnRestoryWallet = document.querySelector('.starter-modal__link_restore-wallet')
это я добавил обработчик. Назвал 'stupied', так как сделал не совсем верно со стороны React.  Как раз из за того что обработчики должны быть в DidMount и WillUnmount

2020-11-03 09:24 UTC, shendel approved these changes

2020-11-03 10:21 UTC, merged