Wallet: change send form
swaponline/MultiCurrencyWallet pull request #3573
Opened 2020-11-16 18:17 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
#3555

### Video / screenshot proof
![image](https://user-images.githubusercontent.com/61930014/99291458-cf103880-287a-11eb-9a1a-1669b90c0c9f.png)
![image](https://user-images.githubusercontent.com/61930014/99291481-db949100-287a-11eb-80ad-439dc2410e51.png)
![image](https://user-images.githubusercontent.com/61930014/99291495-e4856280-287a-11eb-8b27-3247a4066ed8.png)
![image](https://user-images.githubusercontent.com/61930014/99291579-0383f480-287b-11eb-869e-6848a8f07529.png)
![image](https://user-images.githubusercontent.com/61930014/99291609-0e3e8980-287b-11eb-8458-a20b2ab70cb2.png)

2020-11-16 18:36 UTC, noxonsu commented
https://pr3573.swaponline.site/

2020-11-16 21:49 UTC, shendel requested changes

2020-11-16 21:49 UTC, shendel commented on src/front/shared/components/FAQ/FAQ.js
> +            <p className={styles.descriptionFee}><span>BTC:</span> <span className={styles.fee}>{btc.fee}</span> sat/byte</p>
откуда береться config.opts.fee и где он обновляется (dinamicFee) в реальности он может за час прыгать от 70 сатоши за байт до 300 и обратно (посмотри helpers/(btc|eth|host) -> estimateFee) -там расчет фи в зависимости от типа транзакций (отправка или свап) - там использует апи, которое возвращает рекомендованный фи за байт (килобайт) - вот это значение тебе надо ложить в redux и оттуда брать чтобы показать в этом блоке

2020-11-16 21:55 UTC, shendel commented on src/front/shared/components/FAQ/FAQ.js
> +            <p className={styles.descriptionFee}><span>BTC:</span> <span className={styles.fee}>{btc.fee}</span> sat/byte</p>
то что ты добавил (https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/helpers/btc.js#L15) - это админ-фии, сервис-фии - это процент от суммы перевода от 0-до-100 от суммы перевода, который будет отправлен владельцу сайта (если он включит эту опцию у себя в плагине)
Тебе нужно вывести вот это https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/helpers/btc.js#L183
Это (для битка) - рекомендованное количество сатоши (копеек) за каждый байт транзакции
И вот это (для эфира) - https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/helpers/eth.js#L28 - количество gwei (еденица измерения копеек в блокчейне эфира - аналог сатоши в битке, копейке в рубле, центу в долларе)

2020-11-16 22:08 UTC, shendel commented on src/front/shared/components/FAQ/FAQ.js
> +            <p className={styles.descriptionFee}><span>BTC:</span> <span className={styles.fee}>{btc.fee}</span> sat/byte</p>
В данном случае (в helpers/btc -> estimateFee) - hasAdminFee было тобой не правильно трактовано - там это константа, и по этой константе вычисляет размер транзакции (если нет сервис фи - у транзакции один вход - и два выхода (получателю, указанная сумма и остаток/здача - здача), если есть админ(коммисия сервиса) - то выхода три - получателю, здача отправителю - и владельцу сайта коммисия - из-за этого у транзакции разный размер (в байтах) и чтобы транза не зависла - нужно правильно посчитать фии - который равен = сатоши(копейки) за байт умноженное на размер транзакции (в байтах)

2020-11-16 22:11 UTC, shendel commented on src/front/shared/components/FAQ/FAQ.js
> +            <p className={styles.descriptionFee}><span>BTC:</span> <span className={styles.fee}>{btc.fee}</span> sat/byte</p>
а по факту - чтобы было более универсально - использовать minAmount, это константа (есть проблема с отображением в реальном времени) - туда по каждой валюте записывает фи после каждого нового запроса к helpers(coin)->estimateFee

2020-11-16 22:18 UTC, shendel commented on src/front/shared/components/modals/WithdrawModal/WithdrawModal.js
> +    const allowedBalance = new BigNumber(balance).minus(defaultMinFee)
let allowedBalance = ....

2020-11-16 22:19 UTC, shendel commented on src/front/shared/components/modals/WithdrawModal/WithdrawModal.js
> +    const allowedCriptoBalance = temporaryCriptoBalance[0] === '-'
это ужас... (выше let allowedBalance, который уже BigNumber)
allowedBalance = (allowedBalance.isLessThan(0)) ? BigNumber(0) : allowedBalance

2020-11-16 22:21 UTC, shendel commented on src/front/shared/components/modals/WithdrawModal/WithdrawModal.js
> +      : temporaryUsdBalance;
аналогично...
let allowedUsdBalance = BigNumber( allowedBalance * Rate).....
allowedUsdBalance = allowedUsdBalance.isLessThan(0) ? BigNumber(0) : allowedUsdBalance

2020-11-16 22:23 UTC, shendel commented on src/front/shared/components/modals/WithdrawModal/WithdrawModal.js
> +    const criptoValueIsOk = BigNumber(dynamicAmountCriptoValue).isLessThanOrEqualTo(allowedCriptoBalance)
Вот тут  - не бери в расчке что я выше написал - у тебя на выходе число (BigNumber)
if (allowedBalance.isLessThan(0)) {
 criptoValueIsOk = false
.....
}

2020-11-16 22:30 UTC, shendel commented on src/front/shared/components/modals/WithdrawModal/WithdrawModal.js
> +    const allowedCriptoBalance = temporaryCriptoBalance[0] === '-'
или allowedBlance = (allowedBalance.isLessThen(0)) ? allowedBalance.mul(-1) : allowedBalance
но по уму - достаточно доработать контрол Input-a, добавить в него флаг, что только положительные числа, тогда не прийдется во всем проекта делать это.... заодно указать ему тип (type="number"), чтобы на мобиле показывало цифровую клавиатуру, а не кверти

2020-11-17 15:32 UTC, noxonsu commented
- [ ] проверь отправку эфира через metamask

2020-11-18 12:23 UTC, noxonsu commented
https://mainnet3573.swaponline.site/#/

создал эфировский кошелек вижу белый экран ![](https://screenshots.wpmix.net/chrome_1pOihlCNTvHEkRlX1GBxOcIRXRYL7nzB.png)

2020-11-18 17:35 UTC, noxonsu commented
белый экран у меня по прежнему ![](https://screenshots.wpmix.net/chrome_lwMRLjHbxVQuoNKuQJCnPxRzFjOE6eV8.png)

2020-11-19 07:41 UTC, noxonsu commented
коментарий от ux 

Если вы показываете майнинг фи, то можно тогда просто сказать 
The maximum amount you can send is ___ 

Если надо объяснить, то на ховере или под вопросиком можно уточнить The amount should not exceed your current balance minus mining fee

2020-11-19 11:42 UTC, noxonsu commented on src/front/shared/helpers/getPairFees.ts
> +    //@ts-ignore: Property 'coin' does not exist on type 'unknown'
наверно надо убрать игноры

2020-11-19 13:34 UTC, iower commented on src/front/shared/components/FAQ/styles.scss
> +    font-family: 'Lucida Console', Monaco, monospace;
```suggestion
    opacity: 0.7;
    font-family: 'Roboto Mono', monospace;
```

As used in https://github.com/swaponline/MultiCurrencyWallet/blob/master/src/front/shared/pages/Exchange/Exchange.scss#L284

2020-11-19 13:49 UTC, noxonsu approved these changes

2020-11-19 13:49 UTC, merged

2020-11-19 13:59 UTC, iower approved these changes

2020-11-19 13:59 UTC, iower commented on src/front/shared/helpers/getPairFees.ts
>      byCoins[sell.coin] = sell
```suggestion
    const byCoins = {
      [buy.coin]: buy,
      [sell.coin]: sell
    }
```