WIP: TS core
swaponline/MultiCurrencyWallet pull request #3586
Opened 2020-11-18 10:50 UTC by iower

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue

#3172

### Video / screenshot proof

2020-11-26 23:02 UTC, shendel requested changes

2020-11-26 23:02 UTC, shendel commented on src/bot/microbot/actions/swap-flow/index.js
> -export BTC2ETHFlow from './BTC2ETHFlow'
Вот тут всё и сломалось.....
Зачем удалять - тут экспорт классов.....

2020-11-26 23:51 UTC, shendel requested changes

2020-11-26 23:51 UTC, shendel commented on src/common/messaging/pubsubRoom/index.ts
> -class PubSubRoom extends EventEmitter {
default vs not default -  где-то поломалось возможно
... \src\core\swap.room\SwapRoom.ts
import p2pRoom from '../../common/messaging/pubsubRoom'
добавить лог console.log('swap.core->room p2pRoom', p2pRoom)
Проверить, не undefined ли там??

2020-11-26 23:51 UTC, shendel commented
фронт не работает
![image](https://user-images.githubusercontent.com/1880211/100397573-7baca000-305b-11eb-82f4-bf7497a71526.png)

2020-11-26 23:52 UTC, shendel commented
ошибки пост-обработки ts 
![image](https://user-images.githubusercontent.com/1880211/100397596-a139a980-305b-11eb-9385-6c1915b24b56.png)

2020-11-26 23:55 UTC, shendel commented
бот не работает (ну оно-то и ясно - babel знать не знает про .ts в папке /src/bot/)
![image](https://user-images.githubusercontent.com/1880211/100397677-05f50400-305c-11eb-82fb-795f9df78012.png)

2020-11-26 23:58 UTC, shendel commented
а при явном указании пути /src/bot/index.ts не лучше....
![image](https://user-images.githubusercontent.com/1880211/100397702-38066600-305c-11eb-86c2-09030525631b.png)

2020-11-27 09:08 UTC, iower commented
> фронт не работает
> ![image](https://user-images.githubusercontent.com/1880211/100397573-7baca000-305b-11eb-82f4-bf7497a71526.png)

Fixed

2020-11-27 09:08 UTC, iower commented
> ошибки пост-обработки ts
> ![image](https://user-images.githubusercontent.com/1880211/100397596-a139a980-305b-11eb-9385-6c1915b24b56.png)

Fixed

2020-11-27 12:02 UTC, shendel approved these changes

2020-11-27 12:02 UTC, merged