Wallet: send form
swaponline/MultiCurrencyWallet pull request #3678
Opened 2020-11-26 12:14 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
#3643
#3656

### Video / screenshot proof
![after_list](https://user-images.githubusercontent.com/61930014/100349296-30769b00-3023-11eb-8ac0-361f84276f0f.png)
![after_form](https://user-images.githubusercontent.com/61930014/100349300-32405e80-3023-11eb-81fb-7fd88f3b7bb0.png)
![after_form2](https://user-images.githubusercontent.com/61930014/100349309-33718b80-3023-11eb-8b69-c3960f7a1af6.png)

2020-11-26 14:46 UTC, noxonsu commented
![](https://screenshots.wpmix.net/chrome_mpufUHVCkqwfRR1AWQ0naJYubuvI4Qi6.png) 

miner fee при отправке erc20 токенов не может быть 0

2020-11-26 15:43 UTC, noxonsu commented
https://github.com/swaponline/MultiCurrencyWallet/issues/3662

2020-11-26 22:33 UTC, shendel commented
@NotEternal  или они конкретные барыги, или надо делить на десять
Это пи выдает 400???
![image](https://user-images.githubusercontent.com/1880211/100395059-739b3300-3050-11eb-8dd6-23344c8ceeb3.png)
но газ-станция в этот же моменты выдала 40 для fast
![image](https://user-images.githubusercontent.com/1880211/100395090-975e7900-3050-11eb-9e55-16cb081b1835.png)

2020-11-26 22:39 UTC, shendel commented
@NotEternal  это они и есть \\(0-o)// .... странно - разница на десять порядков, между ответом апи и тем что у них на фронте

2020-11-30 11:43 UTC, shendel commented on .github/workflows/nodejs.yml
> +        # npm run bot:test
бот уже не выдает ошибку

2020-11-30 11:43 UTC, shendel requested changes
включить проверку бота

2020-12-01 12:49 UTC, noxonsu commented
## Withdraw: miner fee: ... / service fee: ... #3643

- [] Withdraw: is miner / service fee
- [] Withdraw: fee values seems ok

## btc send: wrong price calculation #3656

- [] Withdraw: btc price seems ok

## erc20 send gas fees 10x that of Metamask #3662

- [] Withdraw: eth mining fee seems ok, not 10x
- [] Exchange: eth mining fee seems ok, not 10x

## Additional

- [] Withdraw: token mining fee seems ok, not 10x
- [] Exchange: token mining fee seems ok, not 10x
- [] Withdraw: admin fee is ok

2020-12-01 12:56 UTC, iower requested changes
# Requested at least 2 approves
-------

My test (in progress)

### Withdraw: miner fee: ... / service fee: ... #3643

- [x] Withdraw: is `miner fee` / `service fee` calculations
---
- [ ] Withdraw: BTC
  * [x] price seems ok
  * [x] miner fee seems ok
  * [x] service fee is ok
  * [x] total calculation is ok
---
- [ ] Withdraw: ETH
  * [x] price seems ok
  * [x] miner fee seems ok, not 10x
  * [ ] service fee is ok
  * [x] total calculation is ok
---
- [ ] Withdraw: token
  - [ ] miner fee seems ok, not 10x
  - [ ] service fee is ok
  - [ ] total calculation is ok

### Additional (separate task?)

- [ ] Exchange: BTC mining fee seems ok, not 10x
- [ ] Exchange: ETH mining fee seems ok, not 10x
- [ ] Exchange: token mining fee seems ok, not 10x

2020-12-01 13:04 UTC, noxonsu requested changes
https://screenshots.wpmix.net/chrome_5wIORcJo3dy9JEq2TS0bUaVEXk8ZNfgq.png

2020-12-01 18:35 UTC, noxonsu commented
- [ ] все фи привести к размерности того что отправляем. т.е. у битка 8 нулей после запятой. сейчас показывает только 6 и округляет. (для эфира 18, для токенов в зависимости от decimals у каждого свой)

2020-12-03 11:29 UTC, noxonsu commented
![](https://screenshots.wpmix.net/chrome_81ZOaqIHXcDhLrkQwAETiFuNtvOmujhi.png) чето ты сложил не так

2020-12-03 13:33 UTC, NotEternal commented
> ![](https://camo.githubusercontent.com/f39c2204fe373f148739ca935a293e04358d9ba7eeecc8c0fef1ca5e8d1ae50c/68747470733a2f2f73637265656e73686f74732e77706d69782e6e65742f6368726f6d655f38315a4f61714948586344684c726b51774145546946754e74764f6d756a68692e706e67) чето ты сложил не так

поправил

2020-12-03 18:36 UTC, shendel approved these changes
This is top

2020-12-03 19:05 UTC, noxonsu approved these changes

2020-12-03 20:03 UTC, shendel approved these changes

2020-12-03 20:04 UTC, merged