WIP: Marketmaker (bot) - Next / Ghost
swaponline/MultiCurrencyWallet pull request #3688
Opened 2020-11-26 22:14 UTC by shendel

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue

#

### Video / screenshot proof

2020-11-26 22:17 UTC, shendel commented on src/common/utils/coin/btc.ts
> +    let adminFee : number | boolean = false
опечатка - админ фи - или false (нету) - или объект { min, процентОтСумы }

2020-12-02 08:38 UTC, noxonsu commented
![](https://screenshots.wpmix.net/putty_OJV7OgqLevL3rIneQBFs3HXFxmIKaWJ5.png) пока еще не похоже на простой запуск (

2020-12-02 09:06 UTC, noxonsu commented
- [ ] "stoploss": 16000 перемиеновать чтоб понятнее было
- [ ] я думаю после должен пройтись @iower чтоб сделать все более юзерфрендли (доки коменты и тп)

2020-12-03 09:48 UTC, iower requested changes
- [ ] Maybe better `USE_JSON` -> `USE_JSON_CONFIG`
- [ ] Pls fix spaces
  - `var: type` - OK
  - `var:type` - not OK
  - `var : type` - not OK

2020-12-03 12:06 UTC, iower requested changes

2020-12-03 13:01 UTC, iower commented on src/bot/.env.example
> +QUICK_START=true|false
```suggestion

```

2020-12-03 16:17 UTC, noxonsu approved these changes

2020-12-03 16:29 UTC, iower commented on src/bot/app/middlewares/prices.ts
> +  if (cachedPrice !== false) return cachedPrice
```suggestion
export const getCoinPrice = async (coin): Promise<BigNumber> => {
  const cachedPrice: number | boolean = getCoinPriceCache(coin)
  if (cachedPrice !== false) {
    return new Promise(() => cachedPrice)
  }
```

2020-12-03 17:27 UTC, iower commented on src/common/domain/network.ts
> +}
```suggestion
export enum Networks {
  mainnet = 'mainnet',
  testnet = 'testnet',
}

export const getNetworkType = (name: string): Networks => {
  switch(name.toLowerCase()) {
    case `mainnet`: return Networks.mainnet
    case `testnet`: return Networks.testnet
  }
  throw new Error('Unknown network')
}
```

2020-12-03 17:30 UTC, iower approved these changes

2020-12-03 17:42 UTC, merged