WIP: Cleanup
swaponline/MultiCurrencyWallet pull request #3697
Opened 2020-11-28 17:36 UTC by iower

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [ ] Tested desktop/mobile
- [ ] Tested bright/dark
- [ ] Tested en/ru
- [ ] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue

#3511

### Video / screenshot proof

2020-11-28 20:54 UTC, shendel requested changes
,.....

2020-11-30 07:33 UTC, iower commented
--- -.- ..--..

2020-12-01 12:44 UTC, noxonsu approved these changes

2020-12-01 12:44 UTC, noxonsu commented on src/front/shared/components/modals/OfferModal/AddOffer/AddOffer.tsx
> +const mathConstants = {
вынести куданить повыше, может еще где будет использовано

2020-12-01 12:45 UTC, noxonsu commented
нэйминг жесть, что проверять??

2020-12-02 13:15 UTC, merged