TypeScript @ts-ignore: estimateFeeValue
swaponline/MultiCurrencyWallet pull request #3758
Opened 2020-12-07 07:14 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
#3562

2020-12-07 10:22 UTC, iower commented on src/front/shared/helpers/btc.ts
> +  speed: string
```suggestion
  speed: 'fast' | 'normal' | 'slow'
```

2020-12-07 10:22 UTC, iower commented on src/front/shared/helpers/ghost.ts
> +  speed: string
```suggestion
  speed: 'fast' | 'normal' | 'slow'
```

2020-12-07 10:23 UTC, iower requested changes

2020-12-07 10:23 UTC, iower commented on src/front/shared/helpers/next.ts
> +  speed: string
```suggestion
  speed: 'fast' | 'normal' | 'slow'
```

2020-12-07 10:41 UTC, iower commented
# Requesting 2 approvals for this PR

2020-12-08 10:57 UTC, shendel approved these changes

2020-12-08 13:28 UTC, iower approved these changes

2020-12-08 13:28 UTC, merged