add comment to send form
swaponline/MultiCurrencyWallet pull request #3859
Opened 2020-12-21 12:46 UTC by UnimixPro

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
add a comment row to send form, and some small bugs

#

### Video / screenshot proof

2020-12-21 18:42 UTC, noxonsu commented
- [ ] сделай комент однострочным пожалуйста

2020-12-23 15:14 UTC, iower requested changes
- [ ] Fix padding jump
![image](https://user-images.githubusercontent.com/35522011/103010981-fe415600-455a-11eb-92db-98f3071afa13.png)
- [ ] Fix codestyle (spaces/indents/semicolons), remove debug output
- [ ] Add translations

2020-12-23 17:15 UTC, noxonsu approved these changes

2020-12-23 18:34 UTC, iower approved these changes

2020-12-23 18:34 UTC, merged