metamask atention when swap
swaponline/MultiCurrencyWallet pull request #3876
Opened 2020-12-23 21:42 UTC by shendel

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] Good naming, keep simple
- [x] Tested desktop/mobile
- [x] Tested bright/dark
- [x] Tested en/ru
- [x] Affects money; I checked the functionality once again
- [x] I checked the PR once again

### Original issue
https://github.com/swaponline/MultiCurrencyWallet/issues/3874
#

### Video / screenshot proof
![image](https://user-images.githubusercontent.com/1880211/103039009-ea104f80-4580-11eb-8f4f-7187208235a5.png)

2020-12-24 06:48 UTC, noxonsu commented
Текст поменяй на "пожалуйста подтвердите транзакцию в вашем кошельке"

2020-12-24 10:47 UTC, shendel commented
https://www.youtube.com/watch?v=ecIIE2fvc6U&feature=youtu.be

2020-12-24 14:33 UTC, noxonsu commented
ща бота починим и глянем

2020-12-24 15:03 UTC, iower requested changes
- [x] ETH-metamask -> BTC: the message shows too early

2020-12-24 21:05 UTC, shendel commented
dont-merge

2020-12-24 22:26 UTC, shendel commented
- [ ] @iower повторно проверь, второй вариант - после свапа - второй свап сразу (пока транзакция весит в мем-пуле)

2020-12-28 14:23 UTC, iower requested changes
- [ ] `partical` -> `participant`

2020-12-29 12:36 UTC, noxonsu commented
проверка сообщения о мемпуле. 
1. залогинился под метамаском 0x86 стартанул обмен eth->btc дождался пока появится транза btc
2. переконектился к другому метамаску, запустил свап. ждал btc никаких сообщений не было, потом появилась транза из п 1 https://screenshots.wpmix.net/chrome_3vTUffhfVaP1kHfpfP4iTVRvFjjwlBcR.png

2020-12-29 14:13 UTC, iower commented on src/front/shared/localisation/ru.json
> +    "message": "Свап стоит на паузе, потому-что у продавца есть не подтвержденные транзакции в мем-пуле. Ждем подтверждения",
```suggestion
    "message": "Свап стоит на паузе, потому что у вас есть не подтвержденные транзакции в мемпуле. Ждем подтверждения.",
    "files": [
      "src/front/shared/pages/Swap/UTXOSwap/SwapProgress/SwapProgress.tsx"
    ]
  },
  {
    "id": "Swap_SellerHasLockedUTX",
    "message": "Свап стоит на паузе, потому что у продавца есть не подтвержденные транзакции в мемпуле. Ждем подтверждения.",
```

2020-12-29 15:37 UTC, noxonsu commented
короче из предыдущего теста, дождался когда можно будет сделать рефанд, сделал его. далее когда перехожу на обменник он пишет что  уменя не завершенный свап и пытается пополнить свап другой, который тоже уже протух давно, причем если жат отмену начинается спам метамаском на подверждение тарныз

2020-12-30 18:50 UTC, merged