fix error
swaponline/MultiCurrencyWallet pull request #3949
Opened 2021-01-18 12:06 UTC by ppaycc

fix error

2021-01-19 11:17 UTC, iower requested changes
Thanks for the pull request!
A couple of thoughts on how you can improve this

2021-01-19 11:17 UTC, iower commented on src/front/shared/components/layout/Center/Center.tsx
> +const Center = ({ children, scrollable, centerHorizontally, centerVertically, keepFontSize, relative, ...rest }: CenterProps) => {
```suggestion
const Center = ({ children, scrollable = false, centerHorizontally = true, centerVertically = true, keepFontSize = false, relative = false, ...rest }: CenterProps) => {
```

2021-01-19 11:17 UTC, iower commented on src/front/shared/components/layout/Center/Center.tsx
>  Center.defaultProps = {
`Center.defaultProps` will be useless after suggestion above - please remove

2021-01-20 14:17 UTC, noxonsu approved these changes

2021-01-20 14:18 UTC, merged