add npm adutit
swaponline/MultiCurrencyWallet pull request #4131
Opened 2021-03-17 16:28 UTC by noxonsu

ref https://github.com/bitcoinjs/bitcoinjs-lib/pull/1672/files

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [ ] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [ ] I tested desktop/mobile resolution
- [ ] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [ ] I checked the **PR** once again

### Original issue

#

### Video / screenshot proof

2021-03-17 17:00 UTC, noxonsu commented
показывает кучу уязвимостей с eliptic походу надо их добавить в вайтлист

2021-03-18 12:25 UTC, iower requested changes
- [x] `install.json` - unnecessary file?
- [x]  `.gitignore` unnecessary line `swaponline.github.io`?

2021-03-18 12:25 UTC, iower commented on .gitignore
> +swaponline.github.io
```suggestion
```

2021-03-18 13:47 UTC, noxonsu commented on .gitignore
> +swaponline.github.io
эта штука нужно потому что я закомитил билд который остался после публикации мейннета, пришлось удалять

2021-03-19 10:55 UTC, merged