Withdraw: extra shadow; Wallet: excess second metamask icon
swaponline/MultiCurrencyWallet pull request #4456
Opened 2021-05-23 09:35 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [ ] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [ ] I tested desktop/mobile resolution
- [x] I tested light/dark theme
- [ ] I tested different languages
- [x] I checked the functionality once again (**AFFECT MONEY**)
- [x] I checked the **PR** once again

### Original issue
#3655

### Video / screenshot proof
![deletedMetamaskIcon](https://user-images.githubusercontent.com/61930014/119255200-0c35ea00-bb80-11eb-9e23-28640a08cfcb.png)
===

![deletedShadow](https://user-images.githubusercontent.com/61930014/119255202-0fc97100-bb80-11eb-872a-90b741770d95.png)

2021-05-23 19:25 UTC, shendel commented
"Wallet: excess second metamask icon" - это на кнопке connect минус иконка?

2021-05-23 19:29 UTC, shendel commented
![image](https://user-images.githubusercontent.com/1880211/119273983-3f2abd00-bc16-11eb-82e8-766beda44c59.png)
****
кто вместо значка эфира лису поставил - хз, но в опере вот так (до этого пула)

2021-05-23 19:30 UTC, shendel requested changes
.

2021-05-23 19:33 UTC, shendel commented
далее - в этом поле аналогично - либо вернуть значок - либо для "External wallet" ставить тот, что определило 
![image](https://user-images.githubusercontent.com/1880211/119274084-d98b0080-bc16-11eb-9311-2b9eab565db8.png)

2021-05-23 19:39 UTC, shendel commented
я думаю второе - разобраться откуда появилась лиса вместо эфира для внешнего - и туда подключить иконку реального встроенного кошелька из common

2021-05-24 06:59 UTC, NotEternal commented
> я думаю второе - разобраться откуда появилась лиса вместо эфира для внешнего - и туда подключить иконку реального встроенного кошелька из common

я поставил вместо иконки эфира. Можно же не только эфир подключать теперь

![Screenshot 2021-05-24 01:55:25](https://user-images.githubusercontent.com/61930014/119309230-a73bcc00-bc33-11eb-9f9e-a9b893011b8f.png)

2021-05-24 11:39 UTC, shendel approved these changes

2021-05-24 19:58 UTC, merged