(WIP) External wallet: connection
swaponline/MultiCurrencyWallet pull request #4775
Opened 2021-09-10 15:05 UTC by NotEternal

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/MultiCurrencyWallet/blob/master/docs/CONTRIBUTING.md) guide
- [ ] Good naming (as clear and simple as possible)
- [ ] Correct behavior if external API endpoints are down, return 404, 504 (or no answer), 401 errors (ddos simulation)
- [ ] I tested desktop/mobile resolution
- [ ] I tested light/dark theme
- [ ] I tested different languages
- [ ] I checked the functionality once again (**AFFECT MONEY**)
- [ ] I checked the work on the Testnet
- [ ] I checked the work on the Mainnet
- [ ] I checked the work in the plugin
- [ ] I checked the **PR** once again

## Tests

Please start auto tests as follows:

- add a label <ins>swap test</ins> to start swap tests
- add a label <ins>withdraw test</ins> to start withdraw tests

You can skip these tests if you completely sure that your changes aren't related to this functional

### Original issue
#4765

### Video / screenshot proof
![image](https://user-images.githubusercontent.com/61930014/132875248-bc976e15-abfd-4baf-b867-d544c48dffc8.png)

2021-09-10 15:10 UTC, developer24-exe commented
builded https://testnet4775.swaponline.site ;

2021-09-10 15:37 UTC, developer24-exe commented
commit 8ce9039dd rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-11 21:25 UTC, shendel requested changes

2021-09-11 21:25 UTC, shendel commented on src/common/web3connect/index.ts
> +  _cachedWeb3: IEtheriumProvider | null = null
Чем _cachedProvider не устроил?
Дубль объекта

2021-09-11 21:32 UTC, shendel commented on src/common/web3connect/index.ts
> +      const _web3provider = await this._cachedProvider.getProvider()
Сдесь уже объект Web3, у которого есть поле 'eth'

2021-09-11 21:33 UTC, shendel commented on src/common/web3connect/index.ts
> +      this._cachedWeb3 = new Web3(_web3provider)
Создание нового Web3 объекта из объекта Web3

2021-09-11 21:36 UTC, shendel commented on src/common/web3connect/providers/InjectedProvider.ts
> -      await window.ethereum.enable()
У оперы по документации надо явный enable, если один раз дали разрешение, окон не будет, но и без enable работать не будет

2021-09-11 21:39 UTC, shendel submitted a review, later dismissed
Тут только UI?

2021-09-12 13:35 UTC, developer24-exe commented
commit 8b8dcfd53 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 04:39 UTC, developer24-exe commented
commit e1f973eca rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 05:23 UTC, developer24-exe commented
commit 8caebb029 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 08:53 UTC, developer24-exe commented
commit 3520c4c25 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 10:17 UTC, developer24-exe commented
commit 71412f809 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 12:51 UTC, developer24-exe commented
commit 46d0fe245 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-13 16:20 UTC, noxonsu approved these changes

2021-09-13 16:20 UTC, noxonsu commented
подключился с матика, с китайского валета, все ок

2021-09-14 05:39 UTC, VitaliyShulik approved these changes

2021-09-14 07:21 UTC, developer24-exe commented
commit f52b1dd83 rebuilded https://testnet4775.swaponline.site https://mainnet4775.swaponline.site

2021-09-14 09:00 UTC, merged